name: amber-utils
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:

# General
    # Python / pip
    - python >=3.9
    - pip  # python packaging tool

    # Utils
    - netCDF4

    # Numerical
    - numpy  # multidimensional array support
    - pandas  # csv support

# Dev
    # Automatic linters / checkers / tests / CI
    - pre-commit  # runs pre commit/push hooks
    - black  # code formatter
    - flake8  # pep8 linter
    - autoflake  # remove unused imports / variables

    # Non-automatic linters / checkers / tests / CI
    - mypy  # type checker
    - coverage  # code coverage
    - pytest  # python testing framework
    - cruft # keep up with cookiecutter updates

    # Docs
    - sphinx  # documentation framework, uses restructured text (.rst)
    - sphinx_rtd_theme  # nice theme for sphinx
