name: mdutils
channels:
  - nodefaults
  - https://conda.anaconda.org/conda-forge
dependencies:
# General
    # Python / pip
    - python=3.11
    - pip>=24.0  # python packaging tool

# Specific
    # Utils
    - netCDF4
    - jinja2
    - pyyaml

    # Numerical / Sci
    - numpy
    - pandas

# Dev
    # Automatic linters / checkers / tests / CI
    - pre-commit  # runs pre commit/push hooks
    - black  # code formatter
    - flake8  # pep8 linter
    - autoflake  # remove unused imports / variables

    # Non-automatic linters / checkers / tests / CI
    - mypy  # type checker
    - pytest  # python testing framework
    - cruft # keep up with cookiecutter updates
