r"""Useful unit conversion factors"""
AMBER_VELOCITIES_SCALE_FACTOR = 20.455

AVOGADROS_NUMBER = 6.022140857e23  # Equal to ase.units._Nav
GRAMS_PER_MILLILITER_TO_GRAMS_PER_MOLE_PER_ANGSTROM_CUBED = AVOGADROS_NUMBER / 1e24  # 0.602214076

EV_TO_JOULE = 1.6021766208e-19  # Equal to ase.units._e (electron charge)
JOULE_TO_EV = 1 / EV_TO_JOULE

KCAL_TO_JOULE = 4184.0  # exact
JOULE_TO_KCAL = 1 / KCAL_TO_JOULE

EV_TO_KCALPERMOL = EV_TO_JOULE * JOULE_TO_KCAL * AVOGADROS_NUMBER
KCALPERMOL_TO_EV = 1 / EV_TO_KCALPERMOL

ANG_TO_METER = 1e-10  # exact
METER_TO_ANG = 1 / ANG_TO_METER

HOUR_TO_SECOND = 3600  # exact
SECOND_TO_HOUR = 1 / HOUR_TO_SECOND  # exact

MIN_TO_SECOND = 60  # exact
SECOND_TO_MIN = 1 / MIN_TO_SECOND  # exact

SECOND_TO_MILLISECOND = 1000  # exact
MILLISECOND_TO_SECOND = 1 / SECOND_TO_MILLISECOND  # exact

NANOSECOND_TO_PICOSECOND = 1000  # exact
PICOSECOND_TO_NANOSECOND = 1 / NANOSECOND_TO_PICOSECOND  # exact

PICOSECOND_TO_FEMTOSECOND = 1000  # exact
FEMTOSECOND_TO_PICOSECOND = 1 / PICOSECOND_TO_FEMTOSECOND

FEMTOSECOND_TO_TIME_AU = 0.09822694788464063  # Equal to ase.units.fs
TIME_AU_TO_FEMTOSECOND = 1 / FEMTOSECOND_TO_TIME_AU

PICOSECOND_TO_TIME_AU = PICOSECOND_TO_FEMTOSECOND * FEMTOSECOND_TO_TIME_AU
TIME_AU_TO_PICOSECOND = 1 / PICOSECOND_TO_TIME_AU

PASCAL_TO_PRESSURE_AU = JOULE_TO_EV / METER_TO_ANG**3
PRESSURE_AU_TO_PASCAL = 1 / PASCAL_TO_PRESSURE_AU

BAR_TO_PASCAL = 1e5  # exact
PASCAL_TO_BAR = 1 / BAR_TO_PASCAL

BAR_TO_PRESSURE_AU = BAR_TO_PASCAL * PASCAL_TO_PRESSURE_AU
PRESSURE_AU_TO_BAR = 1 / BAR_TO_PRESSURE_AU

MEGABAR_TO_PASCAL = 1e11  # exact
PASCAL_TO_MEGABAR = 1 / MEGABAR_TO_PASCAL

MEGABAR_TO_PRESSURE_AU = MEGABAR_TO_PASCAL * PASCAL_TO_PRESSURE_AU
PRESSURE_AU_TO_MEGABAR = 1 / MEGABAR_TO_PRESSURE_AU
