name: black
on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  black:
    name: Black formatting
    runs_on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: echo "nothing"

    - name: Check formatting with black
      run: black amber_utils --check
